In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [4]:
train=pd.read_csv("C:\\CSV Files\\train.csv")        #house price prediction
test=pd.read_csv("C:\\CSV Files\\test.csv")
print("shape of train data: ",train.shape)
print("shape of test data: ",test.shape)

shape of train data:  (1460, 81)
shape of test data:  (1459, 80)


In [5]:
X_train=train.drop(columns="SalePrice", axis=1)      # X_train as matrix and y_train is vector
y_train=train["SalePrice"]
X_test=test.copy()
print("shape of X_train data df: ",X_train.shape)
print("shape of y_train data df: ",y_train.shape)
print("shape of x_test data df: ",X_test.shape)

#our data is trained

shape of X_train data df:  (1460, 80)
shape of y_train data df:  (1460,)
shape of x_test data df:  (1459, 80)


# missing value imputation

In [7]:
isnull_sum=X_train.isnull().sum()
isnull_sum

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MiscVal            0
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
Length: 80, dtype: int64

In [9]:
num_vars=X_train.select_dtypes(['int64','float64']).columns      #find null values in numerical var
num_vars_miss=[var for var in num_vars if isnull_sum[var]>0]
num_vars_miss

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [ ]:
# same for categorical variable

In [10]:
cat_vars=X_train.select_dtypes(['object']).columns      #find null values in categorical var
cat_vars_miss=[var for var in cat_vars if isnull_sum[var]>0]
cat_vars_miss

['Alley',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [ ]:
#our strategy is to impute some columns by mean and some columns by mode values , but this cant happen by 
#simple imputer class strategy
#for this reason we need to create a pipeline class for this 

In [12]:
num_var_mean=["LotFrontage"]            
num_var_median=["MasVnrArea", "GarageYrBlt"]

cat_vars_mode=['Alley',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu']

cat_vars_missing=['GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']      # we give different columns and apply diff strategy on that i.e mean median mode and constant

In [ ]:
# now apply this we need to create pipeline

In [13]:
num_var_mean_imputer=Pipeline(steps=([("imputer", SimpleImputer(strategy="mean"))]))
num_var_median_imputer=Pipeline(steps=([("imputer", SimpleImputer(strategy="median"))]))
cat_vars_mode_imputer=Pipeline(steps=([("imputer", SimpleImputer(strategy="most_frequent"))]))
cat_vars_missing_imputer=Pipeline(steps=([("imputer", SimpleImputer(strategy="constant", fill_value="missing"))]))

#here we created pipeline for diff variable with diff strategy

In [ ]:
#to define for which column which strategy to apply 

In [15]:
preprocessor=ColumnTransformer(transformers=[("mean_imputer", num_var_mean_imputer, num_var_mean),
                                ("median_imputer",num_var_median_imputer,num_var_median),
                               ("mode_imputer",cat_vars_mode_imputer,cat_vars_mode),
                               ("missing_imputer",cat_vars_missing_imputer,cat_vars_missing)])

In [16]:
preprocessor

ColumnTransformer(transformers=[('mean_imputer',
                                 Pipeline(steps=[('imputer', SimpleImputer())]),
                                 ['LotFrontage']),
                                ('median_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['MasVnrArea', 'GarageYrBlt']),
                                ('mode_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond',
                                  'BsmtExposure', 'BsmtFinType1',
                                  'BsmtFinType2', 'Electrical',
                                  'FireplaceQu']),
                                ('missing_imputer',
                                 Pipe

In [17]:
preprocessor.fit(X_train)       # only on train not on test

ColumnTransformer(transformers=[('mean_imputer',
                                 Pipeline(steps=[('imputer', SimpleImputer())]),
                                 ['LotFrontage']),
                                ('median_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['MasVnrArea', 'GarageYrBlt']),
                                ('mode_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond',
                                  'BsmtExposure', 'BsmtFinType1',
                                  'BsmtFinType2', 'Electrical',
                                  'FireplaceQu']),
                                ('missing_imputer',
                                 Pipe

In [18]:
preprocessor.transform

<bound method ColumnTransformer.transform of ColumnTransformer(transformers=[('mean_imputer',
                                 Pipeline(steps=[('imputer', SimpleImputer())]),
                                 ['LotFrontage']),
                                ('median_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['MasVnrArea', 'GarageYrBlt']),
                                ('mode_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond',
                                  'BsmtExposure', 'BsmtFinType1',
                                  'BsmtFinType2', 'Electrical',
                                  'FireplaceQu']),
                                ('missing_im

In [ ]:
#to check statistics of these fit transform i.e for which mean apply same mode and median apply to what

In [19]:
preprocessor.named_transformers_["mean_imputer"].named_steps["imputer"].statistics_

array([70.04995837])

In [ ]:
#is this true ? let us check mean of that column. LotFrontage

In [20]:
train["LotFrontage"].mean()      #same mean means correct 

70.04995836802665

In [ ]:
#we can check same for all remaining 

In [21]:
preprocessor.named_transformers_["median_imputer"].named_steps["imputer"].statistics_

array([   0., 1980.])

In [22]:
preprocessor.named_transformers_["mode_imputer"].named_steps["imputer"].statistics_

array(['Grvl', 'None', 'TA', 'TA', 'No', 'Unf', 'Unf', 'SBrkr', 'Gd'],
      dtype=object)

In [23]:
preprocessor.named_transformers_["missing_imputer"].named_steps["imputer"].statistics_

array(['missing', 'missing', 'missing', 'missing', 'missing', 'missing',
       'missing'], dtype=object)

In [ ]:
# now to impute these on main dataset

In [24]:
X_train_clean=preprocessor.transform(X_train)
X_test_clean=preprocessor.transform(X_test)

In [25]:
X_train_clean     # we  got 2D numpy array 

array([[65.0, 196.0, 2003.0, ..., 'missing', 'missing', 'missing'],
       [80.0, 0.0, 1976.0, ..., 'missing', 'missing', 'missing'],
       [68.0, 162.0, 2001.0, ..., 'missing', 'missing', 'missing'],
       ...,
       [66.0, 0.0, 1941.0, ..., 'missing', 'GdPrv', 'Shed'],
       [68.0, 0.0, 1950.0, ..., 'missing', 'missing', 'missing'],
       [75.0, 0.0, 1965.0, ..., 'missing', 'missing', 'missing']],
      dtype=object)

In [ ]:
#to check how many columns available from main data set

In [26]:
preprocessor.transformers_       # main dataframe contain no missing value that column is droped, 
                            #but if we need not to drop these columns then we need to give value to remainder, i.e passthrough,
                               # by default it takes drop 

[('mean_imputer',
  Pipeline(steps=[('imputer', SimpleImputer())]),
  ['LotFrontage']),
 ('median_imputer',
  Pipeline(steps=[('imputer', SimpleImputer(strategy='median'))]),
  ['MasVnrArea', 'GarageYrBlt']),
 ('mode_imputer',
  Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent'))]),
  ['Alley',
   'MasVnrType',
   'BsmtQual',
   'BsmtCond',
   'BsmtExposure',
   'BsmtFinType1',
   'BsmtFinType2',
   'Electrical',
   'FireplaceQu']),
 ('missing_imputer',
  Pipeline(steps=[('imputer',
                   SimpleImputer(fill_value='missing', strategy='constant'))]),
  ['GarageType',
   'GarageFinish',
   'GarageQual',
   'GarageCond',
   'PoolQC',
   'Fence',
   'MiscFeature']),
 ('remainder',
  'drop',
  [0,
   1,
   2,
   4,
   5,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   27,
   28,
   29,
   34,
   36,
   37,
   38,
   39,
   40,
   41,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   

In [ ]:
# now to convert these numpy2d array into data frame

In [27]:
X_train_clean_miss_vars=pd.DataFrame(X_train_clean, columns=num_var_mean+num_var_median+cat_vars_mode+cat_vars_missing)

In [28]:
X_train_clean_miss_vars       #nulll value imputation done

LotFrontage MasVnrArea GarageYrBlt Alley MasVnrType BsmtQual BsmtCond  \
0           65.0      196.0      2003.0  Grvl    BrkFace       Gd       TA   
1           80.0        0.0      1976.0  Grvl       None       Gd       TA   
2           68.0      162.0      2001.0  Grvl    BrkFace       Gd       TA   
3           60.0        0.0      1998.0  Grvl       None       TA       Gd   
4           84.0      350.0      2000.0  Grvl    BrkFace       Gd       TA   
...          ...        ...         ...   ...        ...      ...      ...   
1455        62.0        0.0      1999.0  Grvl       None       Gd       TA   
1456        85.0      119.0      1978.0  Grvl      Stone       Gd       TA   
1457        66.0        0.0      1941.0  Grvl       None       TA       Gd   
1458        68.0        0.0      1950.0  Grvl       None       TA       TA   
1459        75.0        0.0      1965.0  Grvl       None       TA       TA   

     BsmtExposure BsmtFinType1 BsmtFinType2 Electrical FireplaceQu GarageType  \
0              No          GLQ          Unf      SBrkr          Gd     Attchd   
1              Gd          ALQ          Unf      SBrkr          TA     Attchd   
2              Mn          GLQ          Unf      SBrkr          TA     Attchd   
3              No          ALQ          Unf      SBrkr          Gd     Detchd   
4              Av          GLQ          Unf      SBrkr          TA     Attchd   
...           ...          ...          ...        ...         ...        ...   
1455           No          Unf          Unf      SBrkr          TA     Attchd   
1456           No          ALQ          Rec      SBrkr          TA     Attchd   
1457           No          GLQ          Unf      SBrkr          Gd     Attchd   
1458           Mn          GLQ          Rec      FuseA          Gd     Attchd   
1459           No          BLQ          LwQ      SBrkr          Gd     Attchd   

     GarageFinish GarageQual GarageCond   PoolQC    Fence MiscFeature  
0             RFn         TA         TA  missing  missing     missing  
1             RFn         TA         TA  missing  missing     missing  
2             RFn         TA         TA  missing  missing     missing  
3             Unf         TA         TA  missing  missing     missing  
4             RFn         TA         TA  missing  missing     missing  
...           ...        ...        ...      ...      ...         ...  
1455          RFn         TA         TA  missing  missing     missing  
1456          Unf         TA         TA  missing    MnPrv     missing  
1457          RFn         TA         TA  missing    GdPrv        Shed  
1458          Unf         TA         TA  missing  missing     missing  
1459          Fin         TA         TA  missing  missing     missing  

[1460 rows x 19 columns]

In [29]:
#to check null value imputed or not
X_train_clean_miss_vars.isnull().sum().sum()

0

In [ ]:
#to check what we given to specific column is get imputed , means mode value or mean value

In [31]:
train["Alley"].value_counts()

Grvl    50
Pave    41
Name: Alley, dtype: int64

In [32]:
X_train_clean_miss_vars["Alley"].value_counts()        #mode value i.e. Grvl is imputed in alley column

Grvl    1419
Pave      41
Name: Alley, dtype: int64