In [16]:
import numpy as np

In [2]:
a=[1,2,3]
a

[1, 2, 3]

In [4]:
a

[1, 2, 3]

In [6]:
a=[1,2,3,4,5]
myarr=np.array(a)
myarr

array([1, 2, 3, 4, 5])

In [3]:
a=[]
n=int(input("enter size of array"))
for i in range (n):
    val=int(input("enter number"))
    a.append(val)

myarray=np.array(a)    
myarray    

enter size of array5
enter number1
enter number2
enter number3
enter number4
enter number5


array([1, 2, 3, 4, 5])

In [5]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x            

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
x=np.array(a)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
print("dimension of array= ",x.ndim)
print("shape of array= ",x.shape)

dimension of array=  2
shape of array=  (3, 3)


In [21]:
x.ndim

2

In [22]:
x.shape

(3, 3)

In [23]:
m=np.eye(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
n=np.eye(3,5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [26]:
arr=np.diag([1,5,3,7])
arr

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 7]])

In [29]:
np.diag(arr)

array([1, 5, 3, 7])

In [32]:
ar=np.random.randint(1,10,3)
ar

array([9, 1, 5])

In [39]:
arr=np.random.randn(5)
arr

array([-1.25727479, -0.87021684,  0.88202034, -1.00748462,  0.94761351])

In [39]:
import numpy as np

In [7]:
a=[]
size=int(input("how many numbers ? "))
for i in range(size):
    val=int(input('enter number'))
    a.append(val)
arr=np.array(a)    
for i in range(arr.size):
    print(arr[i])
    
sum=0
for i in range(arr.size):
    sum=sum+arr[i]
print("sum of array= ",sum)    

how many numbers ? 5
enter number2
enter number4
enter number6
enter number8
enter number10
2
4
6
8
10
sum of array=  30


In [10]:
a=[]
size=int(input("how many numbers ? "))
for i in range(size):
    val=int(input('enter number'))
    a.append(val)
arr=np.array(a)    
for i in range(arr.size):
    print(arr[i])
arr1=arr[0:5]    
print(arr1)

how many numbers ? 5
enter number1
enter number2
enter number3
enter number4
enter number5
1
2
3
4
5
[1 2 3 4 5]


In [19]:
ary=np.random.randint(1,50,12)
ary

array([15, 19,  9,  2, 18,  7, 14, 16, 16, 42, 30, 25])

In [20]:
ary.shape

(12,)

In [24]:
ary=ary.reshape(2,6)
ary

array([[15, 19,  9,  2, 18,  7],
       [14, 16, 16, 42, 30, 25]])

In [25]:
ary=ary.reshape(12)
ary

array([15, 19,  9,  2, 18,  7, 14, 16, 16, 42, 30, 25])

In [26]:
ary.ndim

1

In [27]:
ary=ary.reshape(2,2,3)
ary

array([[[15, 19,  9],
        [ 2, 18,  7]],

       [[14, 16, 16],
        [42, 30, 25]]])

In [28]:
ary.ndim

3

In [30]:
ary=ary.reshape(12)
ary

array([15, 19,  9,  2, 18,  7, 14, 16, 16, 42, 30, 25])

In [1]:
import numpy as np

In [19]:
np.random.seed(5)
arr=np.random.randint(1,100,10)
arr

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [19]:
matrix=[]
row=int(input("enter rows: "))
col=int(input("enter columns: "))
for i in range(row):
    for j in range(col):
        a=[]
        val=int(input("enter numbers: "))
        a.append(val)
    matrix.append(a)
arr=np.array(matrix)

enter rows: 3
enter columns: 3
enter numbers: 1
enter numbers: 2
enter numbers: 3
enter numbers: 4
enter numbers: 5
enter numbers: 6
enter numbers: 7
enter numbers: 8
enter numbers: 9


In [21]:
for i in range(row):
    for j in range(col):
        print(arr[i,j],end="  ")
    print()

3  

IndexError: index 1 is out of bounds for axis 1 with size 1

In [23]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.random.seed(111)
m=np.random.randint(1,500,30).reshape(6,5)
m

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [60]:
m[0:1,0:2]

array([[341, 365]])

In [61]:
a=np.array([1,2,3,4,5,6,7,8])
slicing=a[3:6]
slicing[:]=0
a

array([1, 2, 3, 0, 0, 0, 7, 8])

In [62]:
a=np.array([1,2,3,4,5,6,7,8])
slicing=a[3:6].copy()
slicing[:]=0
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
arr=np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [72]:
arr1=np.arange(1,5)
arr1*2

array([2, 4, 6, 8])

In [67]:
arr**2

array([ 1,  4,  9, 16], dtype=int32)

In [68]:
arr+2

array([3, 4, 5, 6])

In [70]:
arr2=np.arange(11,15)
arr2

array([11, 12, 13, 14])

In [73]:
arr1+arr2

array([12, 14, 16, 18])

In [77]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)

In [78]:
a

array([[1, 2],
       [3, 4]])

In [79]:
b

array([[5, 6],
       [7, 8]])

In [80]:
a+b

array([[ 6,  8],
       [10, 12]])

In [81]:
a*b

array([[ 5, 12],
       [21, 32]])

In [82]:
a-b

array([[-4, -4],
       [-4, -4]])

In [83]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [84]:
arr=np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

In [85]:
np.argmin(arr)

0

In [86]:
np.argmax(arr)

5

In [94]:
np.random.seed(111)
arr=np.random.randint(1,21,10)
np.random.shuffle(arr)
arr

array([ 3,  9,  8, 11,  8, 10, 19, 13, 13, 20])

In [95]:
np.unique(arr)

array([ 3,  8,  9, 10, 11, 13, 19, 20])

In [1]:
import pandas as pd